---
title: "STA355H1 - Assignment 2"
output: html_document
---

# Q1 Part 2 (a)

```{r}
n <- 60
m <- matrix(rlogis(10000*n), ncol = n)
# Confidence intervals
theta_hat <- apply(m, 1, median)
W <- rchisq(10000, 2)^2/4
var_hat_theta_hat <- W*4/n
lower <- theta_hat - 1.645*sqrt(var_hat_theta_hat)
upper <- theta_hat + 1.645*sqrt(var_hat_theta_hat)
# Proportion of intervals containing zero
sum(lower <= 0 & upper >= 0)/10000
```

# Q1 Part 2 (b)

```{r}
set.seed(1007941426)
n <- 60
m <- matrix(rlogis(10000*n), ncol = n)
theta_hat <- apply(m, 1, median)
# Bootstrap samples
boot_medians <- matrix(NA, nrow = 10000, ncol = 100)
for (i in 1:10000) {
  boot_samples <- replicate(100, sample(m[i,], size = n, replace = T))
  boot_samples <- t(boot_samples)
  boot_medians[i,] <- apply(boot_samples, 1, median)
}
# Confidence intervals
sd_boot <- apply(boot_medians, 1, sd)
lower <- theta_hat - 1.645*sd_boot
upper <- theta_hat + 1.645*sd_boot
# Proportion of intervals containing zero
sum(lower <= 0 & upper >= 0)/10000
```

```{r}
n <- 500
m <- matrix(rnorm(1000*n), ncol = n)
x_k <- t(apply(m, 1, sort)) # Ordered values
tau_k <- (1:n - 0.5)/n
F_inv <- qnorm(tau_k) # Theoretical quantiles
# Superimposed plot
plot(rep(F_inv, 1000), c(t(x_k)), xlab = "Theoretical quantiles", ylab = "Sample quantiles")
abline(0, 1, col = "red", lwd = 3)
```

```{r}
n <- 500
samples <- matrix(rlogis(1000*n), ncol = n)
x_k <- t(apply(samples, 1, sort)) # Ordered values
tau_k <- (1:n-0.5)/n
F_inv <- qlogis(tau_k) # Theoretical quantiles
# Superimposed plot
plot(rep(F_inv, 1000), c(t(x_k)), xlab = "Theoretical quantiles", ylab = "Sample quantiles")
abline(0, 1, col = "red", lwd = 3)
```

```{r}
incomes <- read.table("incomes.txt")
incomes <- unlist(incomes, use.names = F)
# QQ plot
qqnorm(log(incomes))
qqline(log(incomes), col = "red", lwd = 3)
shapiro.test(log(incomes)) # Shapiro-Wilk test
# Boxplots
boxplot(log(incomes), main = "Boxplot of log(incomes)")
boxplot(rnorm(length(incomes)), main = "Boxplot of a normal sample")
# Line-up plot
library(nullabor)
library(ggplot2)
df <- data.frame(log_inc = log(incomes))
line_up <- lineup(null_dist("log_inc", "normal"), df)
line_up <- line_up[order(line_up$.sample, line_up$log_inc),]
line_up$quantiles <- rep(qnorm((1:200-0.5)/200), 20)
ggplot(line_up, aes(quantiles, log_inc)) + geom_point(cex = .5) + facet_wrap(~ .sample) + labs(title = "Line-up of QQ-plots", x = "Quantiles", y = "Log(income)") + theme_minimal()
```

```{r}
gini <- function(x) {
  # Compute the point estimate
  n <- length(x)
  x <- sort(x)
  wt <- (2*c(1:n) - 1)/n - 1
  g <- sum(wt*x)/sum(x)
  # Compute leave-one-out estimates
  wt1 <- (2*c(1:(n-1)) - 1)/(n-1) - 1
  gi <- NULL
  for (i in 1:n) {
    x1 <- x[-i] # Data with x[i] deleted
    gi <- c(gi, sum(wt1*x1) / sum(x1))
  }
  # Compute the jackknife SE estimate
  gbar <- mean(gi)
  jk <- sqrt((n-1)*sum((gi-gbar)^2)/n)
  # Compute the bootstrap SE estimate
  boot <- NULL
  for (i in 1:1000) {
    y <- sample(x, size = 200, replace = T)
    y <- sort(y)
    boot <- c(boot, sum(wt*y)/sum(y))
  }
  return(list(gini = g, jackknife = jk, bootstrap = sd(boot)))
}

# Compute an estimate of the Gini index and its SE estimates
r <- gini(incomes)
r$gini
r$jackknife
r$bootstrap

# Empirical Lorenz curve
plot(c(1:500)/500, cumsum(sort(x))/sum(x), type = "l", lwd = 4, col = "red", xlab = "Cumulative proportion", ylab = "Quantile")
abline(0, 1, lty = 2, lwd = 2)
```
